### ISSUE TITLE
Add contributions information to the README

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/app-registry#30]
### Description

Currently, the README doesn't provide instructions for the users to submit a PR with the off-chain information for the sidechain applications.

### Acceptance Criteria

- The contributions section in the README is updated with proper instructions for users to submit a PR

### Additional Information

Ref: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by elidakirigo** [comment]
hi, I'd like to contribute to the documentation of this project.

**Comment by sameersubudhi** [comment]
Hi @elidakirigo, Please feel free to raise a PR with your contributions.

**Comment by elidakirigo** [comment]
thanks @sameersubudhi
